export const fieldsNotConsideredOnComparison = [
  "salePrice",
  "manufacturerName",
  "grossPrice",
  "BUP_UOM",
  "BUP_Value",
  "uom",
  "productImage",
  "BUP_Conversion",
  "minQuantity",
  "manufacturerImage",
  "name",
  "listPrice",
  "channel",
  "display",
  "atp",
];
