export const tableFields = [
  "Toepassing",
  "salePrice",
  "Hardheid",
  "grossPrice",
  "Artikelnummer",
  "stepQuantity",
  "uom",
  "Kleur",
  "Temperatuurgebied",
  "minQuantity",
  "Materiaal",
  "sku",
  "Snoerdikte",
  "Inwendige diameter",
  "Maat volgens AS568",
  "listPrice",
  "channel",
];
